# .labrador.example.yaml - Example Labrador configuration file.

###########################################################
# Output options
###########################################################

# Highly detailed debug output. Includes verbose.
debug: true

# More detailed output.
verbose: true

# Only show the final result, without the banner or info.
quiet: false

# Surround values in double quotes and escape existing double quotes.
quote: false

# Option to write gathered variables/values to a file.
outfile:
  # File path.
  path: local.env
  # File permisson mode.
  mode: '660'


###########################################################
# AWS options
###########################################################

aws:

  # Explicitly set the AWS region. This can also be set with the
  # standard AWS environment variables, or a CLI option.
  #region: us-east-1

  # List of AWS Secrets Manager secret names to fetch.
  # Each secret can hold multiple key/value pairs. All are pulled.
  sm_secret:
  - name/of/one
  - name/of/two

  # List of AWS SSM Parameter Store paths to recursively fetch.
  # Each item can be a single param, or a wildcard path to pull all params.
  ssm_param:
  - /path/to/single/param
  - /path/to/wildcard/params/*
