# .labrador.example.yaml - Example Labrador configuration file.

###########################################################
# Display options
###########################################################

# Highly detailed debug output. Includes verbose.
debug: true

# More detailed output.
verbose: true

# Only show the final result, without the banner or info.
quiet: false


###########################################################
# Output options
###########################################################

# Variable key/value transformation options.
transform:
  # Surround values in double quotes and escape existing double quotes.
  quote: false
  # Make all variable names lower case.
  lower: false
  # Make all variable names upper case.
  upper: false

# Option to write gathered variables/values to a file.
outfile:
  # File path.
  path: .env
  # File permisson mode.
  mode: '660'


###########################################################
# AWS options
###########################################################

aws:

  # Explicitly set the AWS region. This can also be set with the
  # standard AWS environment variables, or a CLI option.
  #region: us-east-1

  # List of AWS Secrets Manager secret names to fetch.
  # Each secret can hold multiple key/value pairs. All are pulled.
  sm_secret:
  - name/of/one
  - name/of/two

  # List of AWS SSM Parameter Store paths to recursively fetch.
  # Each item can be a single param, or a wildcard path to pull all params.
  ssm_param:
  - /path/to/single/param
  - /path/to/wildcard/params/*


###########################################################
# GCP options
###########################################################

gcp:

  # List of GCP Secret Manager secret names to fetch.
  # Secrets can specify an explicit version, or default to latest.
  # Format must be one of:
  #     projects/<project name>/secrets/<secret name>
  #     projects/<project name>/secrets/<secret name>/versions/<version>
  sm_secret:
    - projects/my-first-project/secrets/name-of-secret1
    - projects/my-other-project/secrets/name-of-secret2/versions/1
